repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.10.1'
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        args:
        - --show-source
        - --config=setup.cfg
